default: &default
  adapter: postgresql
  encoding: unicode

  username: ibraa
  password: <%= ENV["BACKEND_DATABASE_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tet_hub

production:
  <<: *default
  
